### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by bdeadman** [open-reaction-database/ord-schema#740]
**Describe the bug**
[The front page of ORD docs](https://docs.open-reaction-database.org/en/latest/) has a broken YouTube video at the bottom. 

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/6d0a4c1a-c1a6-4a6b-b277-2cf6e8e8e3d1)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome (126.0.6478.128), Edge (126.0.2592.102) and Firefox (126.0.1)

**Additional context**
I expected to find the code for this page in https://github.com/open-reaction-database/ord-schema/blob/52b7da36b22faaa6e15f20173962e127a62e21b9/docs/index.rst but the YouTube link does not appear to be there.

**Comment by bdeadman** [comment]
The video is at [https://youtu.be/UyHVwJUBDIk](https://youtu.be/UyHVwJUBDIk) but set to private. Could this be in your YouTube account @skearnes @connorcoley?

**Comment by skearnes** [comment]
I think this was the RDKit UGM video; maybe @greglandrum made it private recently?

**Comment by bdeadman** [comment]
I thought it may have been one of these videos [https://www.youtube.com/@openreactiondatabase9685](https://www.youtube.com/@openreactiondatabase9685) which are publicly available, but the settings may have changed to prevent embedding.

Do you know where the link is contained in the docs code?  I was expecting to see it in [index.rst](https://github.com/open-reaction-database/ord-schema/blob/52b7da36b22faaa6e15f20173962e127a62e21b9/docs/index.rst) but this looks like it has everything but the embedded video. If I can find it I will make a temporary fix by removing the video or redirecting it.

**Comment by greglandrum** [comment]
> I think this was the RDKit UGM video; maybe @greglandrum made it private recently

To make presenters more comfortable and since the UGM videos generally don't age well, we "take them down" (i.e. make them private) after a couple of years.

@skearnes  if you and @connorcoley want this one public again, I'm happy to change its visibility

**Comment by skearnes** [comment]
@greglandrum I think making that public again would be great; the concept overview is still very useful. Thanks!

**Comment by greglandrum** [comment]
> @greglandrum I think making that public again would be great; the concept overview is still very useful. Thanks!

Done.

**Comment by bdeadman** [comment]
Note to self: The link to the video is contained here [](https://github.com/open-reaction-database/ord-schema/blob/main/docs/index.rst?plain=1#L33).

**Comment by bdeadman** [comment]
The video is still showing as private. #745 removes this YouTube link and adds a link to the [ORD YouTube channel](http://www.youtube.com/@openreactiondatabase9685) instead.

**Comment by skearnes** [comment]
> > @greglandrum I think making that public again would be great; the concept overview is still very useful. Thanks!
> 
> Done.

@greglandrum the video is still showing as private? https://www.youtube-nocookie.com/embed/UyHVwJUBDIk?start=3

**Comment by greglandrum** [comment]
> > > @greglandrum I think making that public again would be great; the concept overview is still very useful. Thanks!
> > 
> > 
> > Done.
> 
> @greglandrum the video is still showing as private? https://www.youtube-nocookie.com/embed/UyHVwJUBDIk?start=3

Weird. I'm not sure whaI did wrong.
It's actually public now and your link above works.

**Comment by skearnes** [comment]
@greglandrum thanks!

**Comment by bdeadman** [comment]
Thanks @greglandrum. I have now created PR #749 to re-embed the video link in the docs front page. This PR also updates your affiliation in the advisory board list.

Closing issue as resolved.

**Comment by greglandrum** [comment]
Thanks for updating my affiliation @bdeadman
